"""empty message

Revision ID: 9f7a87e60d45
Revises: e7b7b12d5fa1
Create Date: 2024-02-28 21:42:54.789989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7a87e60d45'
down_revision = 'e7b7b12d5fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harmonium', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.drop_column('level')
        batch_op.drop_column('asana_focus')

    with op.batch_alter_table('meditation', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.drop_column('level')
        batch_op.drop_column('asana_focus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meditation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asana_focus', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('level', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('harmonium', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asana_focus', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('level', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
